apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: opctlnodes.opctl.opctloperator.opctl.io
spec:
  group: opctl.opctloperator.opctl.io
  names:
    kind: OpctlNode
    plural: opctlnodes
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            annotations:
              type: object
            env:
              type: object
            image:
              type: string
            service:
              properties:
                annotations:
                  type: object
                name:
                  type: string
                servicetype:
                  type: string
              type: object
          type: object
        status:
          properties:
            phase:
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
