apiVersion: opctl.opctloperator.opctl.io/v1beta1
kind: OpctlNode
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-node
spec:
  # Add fields here
  image: "opctl/opctl:0.1.24"
  name: operatedopctl
  annotations:
    opctl.io/annotations: "test"
  env:
    environment: dev
  service:
    name: opctl
    servicetype: NodePort
    annotations:
      opctl.io/annotations: "test"